bfb       = apply
uni       = apply
stu       = apply
Higgs      = ignore

[scan]
; min and max for each parameter
mHa       = 1. 62
mHb       = 1.0 124.
mHc       = 125.09 125.09
t1        = -1.284 -1.284 
t2        = 1.309  1.309 
t3        = -1.509 -1.509
vs        = 990. 990.
vx        = 310. 310.
